name: rostrenen_et_moi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: "^0.14.0+2"
  firebase_storage: ^4.0.0
  email_validator: ^1.0.5
  flutter_spinkit: ^4.1.2+1
  image_picker: ^0.6.7+7
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.12.1
  uuid: ^2.2.2
  geolocator: ^6.0.0
  geocoding: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "android/fastlane/metadata/android/fr-FR/images/icon.png"
